# Generated by Django 2.0.7 on 2018-07-27 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0005_auto_20180727_0910'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Companies',
        ),
    ]
