# Generated by Django 2.0.7 on 2018-07-30 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0007_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('price', models.CharField(default='0', max_length=140)),
                ('body', models.TextField()),
                ('date', models.DateTimeField()),
            ],
        ),
        migrations.DeleteModel(
            name='Project',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
