# Generated by Django 2.0.7 on 2018-07-30 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0008_auto_20180730_0844'),
    ]

    operations = [
        migrations.CreateModel(
            name='Companies',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=140)),
                ('email', models.CharField(max_length=140)),
                ('password', models.TextField()),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
