# Generated by Django 2.0.7 on 2018-07-30 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0009_companies'),
    ]

    operations = [
        migrations.CreateModel(
            name='Business',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=140)),
                ('title', models.CharField(max_length=140)),
                ('location', models.TextField()),
                ('description', models.CharField(max_length=140)),
                ('image1', models.ImageField(default='noimage.jpg', upload_to='business')),
                ('image2', models.ImageField(default='noimage.jpg', upload_to='business')),
                ('image3', models.ImageField(default='noimage.jpg', upload_to='business')),
                ('image4', models.ImageField(default='noimage.jpg', upload_to='business')),
                ('image5', models.ImageField(default='noimage.jpg', upload_to='business')),
                ('date', models.DateTimeField()),
            ],
        ),
    ]
