# Generated by Django 2.0.7 on 2018-07-30 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0010_business'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='business',
            name='location',
            field=models.CharField(max_length=140),
        ),
    ]
