# Generated by Django 2.0.7 on 2018-07-30 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0011_auto_20180730_0954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='image1',
            field=models.ImageField(default='noimage.jpg', upload_to='businesspics'),
        ),
        migrations.AlterField(
            model_name='business',
            name='image2',
            field=models.ImageField(default='noimage.jpg', upload_to='businesspics'),
        ),
        migrations.AlterField(
            model_name='business',
            name='image3',
            field=models.ImageField(default='noimage.jpg', upload_to='businesspics'),
        ),
        migrations.AlterField(
            model_name='business',
            name='image4',
            field=models.ImageField(default='noimage.jpg', upload_to='businesspics'),
        ),
        migrations.AlterField(
            model_name='business',
            name='image5',
            field=models.ImageField(default='noimage.jpg', upload_to='businesspics'),
        ),
    ]
