# Generated by Django 2.0.7 on 2018-08-01 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0013_companybusiness'),
    ]

    operations = [
        migrations.AlterField(
            model_name='companybusiness',
            name='phone',
            field=models.CharField(default='', max_length=30),
        ),
    ]
