# Generated by Django 2.0.7 on 2018-08-01 07:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('business', '0014_auto_20180801_0640'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_select', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='companybusiness',
            name='image',
            field=models.ImageField(default='noimage.jpg', upload_to='businessprofile'),
        ),
    ]
