# Generated by Django 2.0.7 on 2018-08-02 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0016_categories'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='category',
        ),
        migrations.AddField(
            model_name='business',
            name='category',
            field=models.ManyToManyField(to='business.Categories'),
        ),
    ]
