# Generated by Django 2.0.7 on 2018-08-02 06:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0017_auto_20180802_0633'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='business',
            name='category',
        ),
        migrations.AddField(
            model_name='business',
            name='category',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.DO_NOTHING, to='business.Categories'),
        ),
    ]
