# Generated by Django 2.0.7 on 2018-08-02 06:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0019_auto_20180802_0642'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='category',
            field=models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, related_name='category_select', to='business.Categories'),
        ),
    ]
