# Generated by Django 2.0.7 on 2018-08-02 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0024_business_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='phone',
            field=models.CharField(max_length=30),
        ),
    ]
