# Generated by Django 2.0.7 on 2018-08-03 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0026_auto_20180802_1025'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='icon',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
