# Generated by Django 2.1 on 2018-08-10 10:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0028_languages'),
    ]

    operations = [
        migrations.AddField(
            model_name='languages',
            name='search_for',
            field=models.CharField(default='Search for', max_length=150),
        ),
        migrations.AlterField(
            model_name='languages',
            name='app_name',
            field=models.CharField(default='Rentals', max_length=150),
        ),
    ]
