# Generated by Django 2.1 on 2018-08-10 10:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0029_auto_20180810_1027'),
    ]

    operations = [
        migrations.RenameField(
            model_name='languages',
            old_name='search_for',
            new_name='a1',
        ),
    ]
