# Generated by Django 2.1 on 2018-08-10 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0030_auto_20180810_1030'),
    ]

    operations = [
        migrations.AddField(
            model_name='languages',
            name='a10',
            field=models.CharField(default='keeped tags', max_length=150),
        ),
        migrations.AddField(
            model_name='languages',
            name='a11',
            field=models.CharField(default='tags', max_length=150),
        ),
        migrations.AddField(
            model_name='languages',
            name='a12',
            field=models.CharField(default='main info', max_length=150),
        ),
        migrations.AddField(
            model_name='languages',
            name='a13',
            field=models.CharField(default='Title', max_length=150),
        ),
        migrations.AddField(
            model_name='languages',
            name='a14',
            field=models.CharField(default='Looking for...', max_length=150),
        ),
        migrations.AddField(
            model_name='languages',
            name='a15',
            field=models.CharField(default='Offered', max_length=150),
        ),
        migrations.AddField(
            model_name='languages',
            name='a16',
            field=models.CharField(default='Price', max_length=150),
        ),
        migrations.AddField(
            model_name='languages',
            name='a17',
            field=models.CharField(default='/ day', max_length=150),
        ),
        migrations.AddField(
            model_name='languages',
            name='a18',
            field=models.CharField(default='Select product location', max_length=150),
        ),
        migrations.AddField(
            model_name='languages',
            name='a19',
            field=models.CharField(default='Use the search bar below to find your location', max_length=150),
        ),
        migrations.AddField(
            model_name='languages',
            name='a2',
            field=models.CharField(default='It is easy to have your product listed.', max_length=150),
        ),
        migrations.AddField(
            model_name='languages',
            name='a20',
            field=models.CharField(default='Tap to select location', max_length=150),
        ),
        migrations.AddField(
            model_name='languages',
            name='a21',
            field=models.CharField(default='Description', max_length=150),
        ),
        migrations.AddField(
            model_name='languages',
            name='a22',
            field=models.CharField(default='Free text', max_length=150),
        ),
        migrations.AddField(
            model_name='languages',
            name='a23',
            field=models.CharField(default='product condition', max_length=150),
        ),
        migrations.AddField(
            model_name='languages',
            name='a24',
            field=models.CharField(default='New', max_length=150),
        ),
        migrations.AddField(
            model_name='languages',
            name='a25',
            field=models.CharField(default='Used', max_length=150),
        ),
        migrations.AddField(
            model_name='languages',
            name='a26',
            field=models.CharField(default='Has warranty', max_length=150),
        ),
        migrations.AddField(
            model_name='languages',
            name='a27',
            field=models.CharField(default='Need warranty', max_length=150),
        ),
        migrations.AddField(
            model_name='languages',
            name='a28',
            field=models.CharField(default='Yes', max_length=150),
        ),
        migrations.AddField(
            model_name='languages',
            name='a29',
            field=models.CharField(default='No', max_length=150),
        ),
        migrations.AddField(
            model_name='languages',
            name='a3',
            field=models.CharField(default='i want to', max_length=150),
        ),
        migrations.AddField(
            model_name='languages',
            name='a30',
            field=models.CharField(default='Will you ship?', max_length=150),
        ),
        migrations.AddField(
            model_name='languages',
            name='a31',
            field=models.CharField(default='Need shipping?', max_length=150),
        ),
        migrations.AddField(
            model_name='languages',
            name='a32',
            field=models.CharField(default='Product image', max_length=150),
        ),
        migrations.AddField(
            model_name='languages',
            name='a33',
            field=models.CharField(default='Similar image', max_length=150),
        ),
        migrations.AddField(
            model_name='languages',
            name='a34',
            field=models.CharField(default='Camera', max_length=150),
        ),
        migrations.AddField(
            model_name='languages',
            name='a35',
            field=models.CharField(default='Library', max_length=150),
        ),
        migrations.AddField(
            model_name='languages',
            name='a36',
            field=models.CharField(default='Submit', max_length=150),
        ),
        migrations.AddField(
            model_name='languages',
            name='a37',
            field=models.CharField(default='Back to home', max_length=150),
        ),
        migrations.AddField(
            model_name='languages',
            name='a4',
            field=models.CharField(default='sell', max_length=150),
        ),
        migrations.AddField(
            model_name='languages',
            name='a5',
            field=models.CharField(default='rent', max_length=150),
        ),
        migrations.AddField(
            model_name='languages',
            name='a6',
            field=models.CharField(default='giveaway', max_length=150),
        ),
        migrations.AddField(
            model_name='languages',
            name='a7',
            field=models.CharField(default='buy', max_length=150),
        ),
        migrations.AddField(
            model_name='languages',
            name='a8',
            field=models.CharField(default='Category', max_length=150),
        ),
        migrations.AddField(
            model_name='languages',
            name='a9',
            field=models.CharField(default='Subcategory', max_length=150),
        ),
        migrations.AlterField(
            model_name='languages',
            name='a1',
            field=models.CharField(default='Submit your product', max_length=150),
        ),
    ]
