# Generated by Django 2.1 on 2018-08-10 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0031_auto_20180810_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='languages',
            name='a38',
            field=models.CharField(default='No products in', max_length=150),
        ),
        migrations.AddField(
            model_name='languages',
            name='a39',
            field=models.CharField(default='category. Submit the first one.', max_length=150),
        ),
        migrations.AddField(
            model_name='languages',
            name='a40',
            field=models.CharField(default='i want to', max_length=150),
        ),
        migrations.AddField(
            model_name='languages',
            name='a41',
            field=models.CharField(default='main info', max_length=150),
        ),
        migrations.AddField(
            model_name='languages',
            name='a42',
            field=models.CharField(default='Update', max_length=150),
        ),
    ]
