# Generated by Django 2.1 on 2018-08-10 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0032_auto_20180810_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='languages',
            name='a43',
            field=models.CharField(default='Apply filters', max_length=150),
        ),
        migrations.AddField(
            model_name='languages',
            name='a44',
            field=models.CharField(default='Account', max_length=150),
        ),
        migrations.AddField(
            model_name='languages',
            name='a45',
            field=models.CharField(default='Nearby', max_length=150),
        ),
        migrations.AddField(
            model_name='languages',
            name='a46',
            field=models.CharField(default='Search', max_length=150),
        ),
        migrations.AddField(
            model_name='languages',
            name='a47',
            field=models.CharField(default='Add your stuff', max_length=150),
        ),
        migrations.AddField(
            model_name='languages',
            name='a48',
            field=models.CharField(default='Hello', max_length=150),
        ),
        migrations.AddField(
            model_name='languages',
            name='a49',
            field=models.CharField(default='How can I help you today?', max_length=150),
        ),
        migrations.AddField(
            model_name='languages',
            name='a50',
            field=models.CharField(default='Search for a product.', max_length=150),
        ),
        migrations.AddField(
            model_name='languages',
            name='a51',
            field=models.CharField(default='Search...', max_length=150),
        ),
        migrations.AddField(
            model_name='languages',
            name='a52',
            field=models.CharField(default='Or browse desired category.', max_length=150),
        ),
        migrations.AddField(
            model_name='languages',
            name='a53',
            field=models.CharField(default='Access a subcategory.', max_length=150),
        ),
        migrations.AddField(
            model_name='languages',
            name='a54',
            field=models.CharField(default='Select desired category.', max_length=150),
        ),
        migrations.AddField(
            model_name='languages',
            name='a55',
            field=models.CharField(default='Access a subcategory.', max_length=150),
        ),
        migrations.AddField(
            model_name='languages',
            name='a56',
            field=models.CharField(default='Products arround the world', max_length=150),
        ),
        migrations.AddField(
            model_name='languages',
            name='a57',
            field=models.CharField(default='Discover the latest products.', max_length=150),
        ),
        migrations.AddField(
            model_name='languages',
            name='a58',
            field=models.CharField(default='FREE', max_length=150),
        ),
        migrations.AddField(
            model_name='languages',
            name='a59',
            field=models.CharField(default='Special deals', max_length=150),
        ),
        migrations.AddField(
            model_name='languages',
            name='a60',
            field=models.CharField(default='Incredible deals, carefully selected for your delight.', max_length=150),
        ),
        migrations.AddField(
            model_name='languages',
            name='a61',
            field=models.CharField(default='Add your stuff', max_length=150),
        ),
    ]
