# Generated by Django 2.1 on 2018-08-10 11:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0034_auto_20180810_1109'),
    ]

    operations = [
        migrations.AddField(
            model_name='languages',
            name='a71',
            field=models.CharField(default='Deal closed?', max_length=150),
        ),
        migrations.AddField(
            model_name='languages',
            name='a72',
            field=models.CharField(default='Tap here to rate the', max_length=150),
        ),
        migrations.AddField(
            model_name='languages',
            name='a73',
            field=models.CharField(default='Aditional images', max_length=150),
        ),
        migrations.AddField(
            model_name='languages',
            name='a74',
            field=models.CharField(default='Camera', max_length=150),
        ),
        migrations.AddField(
            model_name='languages',
            name='a75',
            field=models.CharField(default='Library', max_length=150),
        ),
        migrations.AddField(
            model_name='languages',
            name='a76',
            field=models.CharField(default='No thanks, it is enough.', max_length=150),
        ),
        migrations.AddField(
            model_name='languages',
            name='a77',
            field=models.CharField(default='Products', max_length=150),
        ),
        migrations.AddField(
            model_name='languages',
            name='a78',
            field=models.CharField(default='Favourites', max_length=150),
        ),
        migrations.AddField(
            model_name='languages',
            name='a79',
            field=models.CharField(default='Trades', max_length=150),
        ),
        migrations.AddField(
            model_name='languages',
            name='a80',
            field=models.CharField(default='Offers', max_length=150),
        ),
        migrations.AddField(
            model_name='languages',
            name='a81',
            field=models.CharField(default='No favourites yet. Add a few to keep for later.', max_length=150),
        ),
        migrations.AddField(
            model_name='languages',
            name='a82',
            field=models.CharField(default='for', max_length=150),
        ),
        migrations.AddField(
            model_name='languages',
            name='a83',
            field=models.CharField(default='USD', max_length=150),
        ),
        migrations.AddField(
            model_name='languages',
            name='a84',
            field=models.CharField(default='No trades for your products.', max_length=150),
        ),
        migrations.AddField(
            model_name='languages',
            name='a85',
            field=models.CharField(default='No offers for your products', max_length=150),
        ),
    ]
