# Generated by Django 2.1 on 2018-08-10 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0035_auto_20180810_1116'),
    ]

    operations = [
        migrations.AddField(
            model_name='languages',
            name='a100',
            field=models.CharField(default='FREE', max_length=150),
        ),
        migrations.AddField(
            model_name='languages',
            name='a101',
            field=models.CharField(default='specials', max_length=150),
        ),
        migrations.AddField(
            model_name='languages',
            name='a102',
            field=models.CharField(default='Edit your account', max_length=150),
        ),
        migrations.AddField(
            model_name='languages',
            name='a103',
            field=models.CharField(default='Update your profile information.', max_length=150),
        ),
        migrations.AddField(
            model_name='languages',
            name='a104',
            field=models.CharField(default='Notifications', max_length=150),
        ),
        migrations.AddField(
            model_name='languages',
            name='a105',
            field=models.CharField(default='Sure, why not', max_length=150),
        ),
        migrations.AddField(
            model_name='languages',
            name='a106',
            field=models.CharField(default='No, not now', max_length=150),
        ),
        migrations.AddField(
            model_name='languages',
            name='a86',
            field=models.CharField(default='Create your account', max_length=150),
        ),
        migrations.AddField(
            model_name='languages',
            name='a87',
            field=models.CharField(default='Choose your credentials and create your account', max_length=150),
        ),
        migrations.AddField(
            model_name='languages',
            name='a88',
            field=models.CharField(default='Username', max_length=150),
        ),
        migrations.AddField(
            model_name='languages',
            name='a89',
            field=models.CharField(default='Email', max_length=150),
        ),
        migrations.AddField(
            model_name='languages',
            name='a90',
            field=models.CharField(default='Password', max_length=150),
        ),
        migrations.AddField(
            model_name='languages',
            name='a91',
            field=models.CharField(default='Password again', max_length=150),
        ),
        migrations.AddField(
            model_name='languages',
            name='a92',
            field=models.CharField(default='Phone', max_length=150),
        ),
        migrations.AddField(
            model_name='languages',
            name='a93',
            field=models.CharField(default='Select product location', max_length=150),
        ),
        migrations.AddField(
            model_name='languages',
            name='a94',
            field=models.CharField(default='Use the search bar below to find your location', max_length=150),
        ),
        migrations.AddField(
            model_name='languages',
            name='a95',
            field=models.CharField(default='Tap to select location', max_length=150),
        ),
        migrations.AddField(
            model_name='languages',
            name='a96',
            field=models.CharField(default='Already registered?', max_length=150),
        ),
        migrations.AddField(
            model_name='languages',
            name='a97',
            field=models.CharField(default='Register', max_length=150),
        ),
        migrations.AddField(
            model_name='languages',
            name='a98',
            field=models.CharField(default='Access your account', max_length=150),
        ),
        migrations.AddField(
            model_name='languages',
            name='a99',
            field=models.CharField(default='Back to home', max_length=150),
        ),
        migrations.AlterField(
            model_name='languages',
            name='a68',
            field=models.CharField(default="Don't have an account yet?", max_length=150),
        ),
    ]
