# Generated by Django 2.1 on 2018-08-10 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0036_auto_20180810_1126'),
    ]

    operations = [
        migrations.AddField(
            model_name='languages',
            name='a107',
            field=models.CharField(default='New', max_length=150),
        ),
        migrations.AddField(
            model_name='languages',
            name='a108',
            field=models.CharField(default='Warranty', max_length=150),
        ),
        migrations.AddField(
            model_name='languages',
            name='a109',
            field=models.CharField(default='Featured', max_length=150),
        ),
        migrations.AddField(
            model_name='languages',
            name='a110',
            field=models.CharField(default='Shipping', max_length=150),
        ),
        migrations.AddField(
            model_name='languages',
            name='a111',
            field=models.CharField(default='Purchase', max_length=150),
        ),
        migrations.AddField(
            model_name='languages',
            name='a112',
            field=models.CharField(default='for only $', max_length=150),
        ),
        migrations.AddField(
            model_name='languages',
            name='a113',
            field=models.CharField(default='Rent', max_length=150),
        ),
        migrations.AddField(
            model_name='languages',
            name='a114',
            field=models.CharField(default='Get', max_length=150),
        ),
        migrations.AddField(
            model_name='languages',
            name='a115',
            field=models.CharField(default='for free', max_length=150),
        ),
        migrations.AddField(
            model_name='languages',
            name='a116',
            field=models.CharField(default='added on', max_length=150),
        ),
        migrations.AddField(
            model_name='languages',
            name='a117',
            field=models.CharField(default='in', max_length=150),
        ),
        migrations.AddField(
            model_name='languages',
            name='a118',
            field=models.CharField(default='Share on Facebook', max_length=150),
        ),
        migrations.AddField(
            model_name='languages',
            name='a119',
            field=models.CharField(default='Favourite', max_length=150),
        ),
        migrations.AddField(
            model_name='languages',
            name='a120',
            field=models.CharField(default='Unfavourite', max_length=150),
        ),
        migrations.AddField(
            model_name='languages',
            name='a121',
            field=models.CharField(default='Login to join conversation', max_length=150),
        ),
        migrations.AddField(
            model_name='languages',
            name='a122',
            field=models.CharField(default='Older comments', max_length=150),
        ),
        migrations.AddField(
            model_name='languages',
            name='a123',
            field=models.CharField(default='Report this product', max_length=150),
        ),
        migrations.AddField(
            model_name='languages',
            name='a124',
            field=models.CharField(default='Trade', max_length=150),
        ),
        migrations.AddField(
            model_name='languages',
            name='a125',
            field=models.CharField(default='Offer', max_length=150),
        ),
        migrations.AddField(
            model_name='languages',
            name='a126',
            field=models.CharField(default='Close', max_length=150),
        ),
        migrations.AddField(
            model_name='languages',
            name='a127',
            field=models.CharField(default='Message', max_length=150),
        ),
        migrations.AddField(
            model_name='languages',
            name='a128',
            field=models.CharField(default='Map', max_length=150),
        ),
    ]
