# Generated by Django 2.1 on 2018-08-10 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0037_auto_20180810_1135'),
    ]

    operations = [
        migrations.AddField(
            model_name='languages',
            name='a129',
            field=models.CharField(default='Offer or ask for a difference', max_length=150),
        ),
        migrations.AddField(
            model_name='languages',
            name='a130',
            field=models.CharField(default='Choose the amount and wait for it.', max_length=150),
        ),
        migrations.AddField(
            model_name='languages',
            name='a131',
            field=models.CharField(default='Amount', max_length=150),
        ),
        migrations.AddField(
            model_name='languages',
            name='a132',
            field=models.CharField(default='Ask', max_length=150),
        ),
        migrations.AddField(
            model_name='languages',
            name='a133',
            field=models.CharField(default='You are going to offer', max_length=150),
        ),
        migrations.AddField(
            model_name='languages',
            name='a134',
            field=models.CharField(default='and offer another', max_length=150),
        ),
        migrations.AddField(
            model_name='languages',
            name='a135',
            field=models.CharField(default='and ask for another', max_length=150),
        ),
        migrations.AddField(
            model_name='languages',
            name='a136',
            field=models.CharField(default='You should ask for another $', max_length=150),
        ),
        migrations.AddField(
            model_name='languages',
            name='a137',
            field=models.CharField(default='You should offer another $', max_length=150),
        ),
        migrations.AddField(
            model_name='languages',
            name='a138',
            field=models.CharField(default='Send your offer', max_length=150),
        ),
    ]
