# Generated by Django 2.1 on 2018-08-13 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0038_auto_20180810_1139'),
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('explore', models.TextField()),
                ('book', models.TextField()),
                ('enjoy', models.TextField()),
                ('imagetop', models.ImageField(default='noimage.jpg', upload_to='businessabout')),
                ('missionstatement', models.TextField()),
                ('imagebot', models.ImageField(default='noimage.jpg', upload_to='businessabout')),
            ],
        ),
    ]
