# Generated by Django 2.1 on 2018-08-13 07:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0040_feedback'),
    ]

    operations = [
        migrations.CreateModel(
            name='Socials',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('facebook', models.TextField(validators=[django.core.validators.URLValidator()])),
                ('google', models.TextField(validators=[django.core.validators.URLValidator()])),
                ('twitter', models.TextField(validators=[django.core.validators.URLValidator()])),
                ('youtube', models.TextField(validators=[django.core.validators.URLValidator()])),
                ('pinterest', models.TextField(validators=[django.core.validators.URLValidator()])),
            ],
        ),
    ]
