# Generated by Django 2.1 on 2018-08-13 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0044_feedback_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='feedback',
            name='user',
        ),
    ]
