# Generated by Django 2.1 on 2018-08-16 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0045_remove_feedback_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('imagetop', models.ImageField(default='noimage.jpg', upload_to='services')),
            ],
        ),
    ]
