# Generated by Django 2.1 on 2018-08-16 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0047_auto_20180816_0958'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='coordinates',
            field=models.CharField(default='0', max_length=40),
        ),
    ]
