# Generated by Django 2.1 on 2018-08-17 06:57

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('business', '0049_saved'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saved',
            name='user',
        ),
        migrations.AddField(
            model_name='saved',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
