# Generated by Django 2.1 on 2018-08-17 06:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('business', '0050_auto_20180817_0657'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='saved',
            name='user',
        ),
        migrations.AddField(
            model_name='saved',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usr_select', to=settings.AUTH_USER_MODEL),
        ),
    ]
