# Generated by Django 2.1 on 2018-08-17 06:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0051_auto_20180817_0658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='saved',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='usr_select', to=settings.AUTH_USER_MODEL),
        ),
    ]
