# Generated by Django 2.1 on 2018-08-17 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0052_auto_20180817_0659'),
    ]

    operations = [
        migrations.AddField(
            model_name='companybusiness',
            name='facebook',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AddField(
            model_name='companybusiness',
            name='instagram',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AddField(
            model_name='companybusiness',
            name='linkedin',
            field=models.CharField(default='none', max_length=100),
        ),
        migrations.AddField(
            model_name='companybusiness',
            name='twitter',
            field=models.CharField(default='none', max_length=100),
        ),
    ]
