# Generated by Django 2.1 on 2018-08-17 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0053_auto_20180817_1051'),
    ]

    operations = [
        migrations.RenameField(
            model_name='about',
            old_name='book',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='about',
            old_name='imagebot',
            new_name='image',
        ),
        migrations.RemoveField(
            model_name='about',
            name='enjoy',
        ),
        migrations.RemoveField(
            model_name='about',
            name='explore',
        ),
        migrations.RemoveField(
            model_name='about',
            name='imagetop',
        ),
        migrations.RemoveField(
            model_name='about',
            name='missionstatement',
        ),
        migrations.AddField(
            model_name='about',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
