# Generated by Django 2.1 on 2018-08-17 11:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0056_auto_20180817_1149'),
    ]

    operations = [
        migrations.RenameField(
            model_name='testimonial',
            old_name='title',
            new_name='name',
        ),
    ]
