# Generated by Django 2.1 on 2018-08-22 08:34

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0058_auto_20180820_0653'),
    ]

    operations = [
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('url', models.TextField(blank=True, default='', validators=[django.core.validators.URLValidator()])),
                ('icon', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='Socials',
        ),
        migrations.AlterField(
            model_name='companybusiness',
            name='address',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='companybusiness',
            name='description',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
        migrations.AlterField(
            model_name='companybusiness',
            name='location',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='companybusiness',
            name='phone',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
        migrations.AlterField(
            model_name='companybusiness',
            name='website',
            field=models.URLField(blank=True, default=''),
        ),
    ]
