# Generated by Django 2.1 on 2018-08-22 10:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0061_user_social'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User_Social',
        ),
    ]
