# Generated by Django 2.1 on 2018-08-23 07:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0065_chatreply'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='sender_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender_profile_select', to='business.CompanyBusiness'),
        ),
    ]
