# Generated by Django 2.1 on 2018-08-23 10:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0067_auto_20180823_0957'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='sender_profile',
        ),
    ]
