# Generated by Django 2.1 on 2018-08-24 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0068_remove_chat_sender_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='views',
            field=models.IntegerField(default='0'),
        ),
    ]
