# Generated by Django 2.1 on 2018-08-27 07:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0070_auto_20180824_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ChatReply', to='business.Chat'),
        ),
    ]
