# Generated by Django 2.1 on 2018-08-27 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0072_remove_chat_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='parent',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='business.Chat'),
        ),
    ]
