# Generated by Django 2.1 on 2018-08-27 09:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0073_chat_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chat',
            name='parent',
        ),
    ]
