# Generated by Django 2.1 on 2018-08-28 08:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0076_auto_20180828_0851'),
    ]

    operations = [
        migrations.AddField(
            model_name='chat',
            name='sender_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender_select', to='business.CompanyBusiness'),
        ),
    ]
