# Generated by Django 2.1 on 2018-08-29 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0080_auto_20180829_0738'),
    ]

    operations = [
        migrations.AddField(
            model_name='categories',
            name='slug',
            field=models.SlugField(blank=True, default='default-cat', max_length=60),
        ),
    ]
