# Generated by Django 2.1 on 2018-08-30 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0081_categories_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Home_banner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('top_text', models.CharField(max_length=140)),
                ('mid_text', models.CharField(max_length=140)),
                ('banner', models.ImageField(default='noimage.jpg', upload_to='businesspics/home_banner')),
            ],
        ),
    ]
