# Generated by Django 2.1 on 2018-08-30 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0083_contactdetails'),
    ]

    operations = [
        migrations.CreateModel(
            name='Terms',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('body', models.CharField(max_length=140)),
            ],
        ),
    ]
