# Generated by Django 2.1 on 2018-08-30 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0084_terms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terms',
            name='body',
            field=models.TextField(),
        ),
    ]
