# Generated by Django 2.1 on 2018-08-30 11:54

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0085_auto_20180830_0843'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='terms',
            name='body',
            field=tinymce.models.HTMLField(),
        ),
    ]
