# Generated by Django 2.1 on 2018-09-03 11:09

from django.db import migrations, models
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0087_companybusiness_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='SingleCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
            ],
        ),
        migrations.AlterField(
            model_name='business',
            name='slug',
            field=models.SlugField(blank=True, default='no-slug', max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='categories',
            name='slug',
            field=models.SlugField(blank=True, default='default-cat', max_length=60, unique=True),
        ),
        migrations.AlterField(
            model_name='companybusiness',
            name='description',
            field=tinymce.models.HTMLField(),
        ),
        migrations.AlterField(
            model_name='companybusiness',
            name='slug',
            field=models.SlugField(blank=True, default='user', max_length=60, unique=True),
        ),
    ]
