# Generated by Django 2.1 on 2018-09-03 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0088_auto_20180903_1109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='slug',
            field=models.SlugField(blank=True, max_length=60, unique=True),
        ),
    ]
