# Generated by Django 2.1 on 2018-09-04 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0091_auto_20180903_1114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='slug',
            field=models.SlugField(blank=True, max_length=60),
        ),
        migrations.AlterField(
            model_name='companybusiness',
            name='slug',
            field=models.SlugField(blank=True, default='user', max_length=60),
        ),
    ]
