# Generated by Django 2.1 on 2018-09-05 08:49

from django.db import migrations
import places.fields


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0093_auto_20180905_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='location',
            field=places.fields.PlacesField(max_length=255),
        ),
    ]
