# Generated by Django 2.1 on 2018-09-05 08:51

from django.db import migrations, models
import places.fields


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0094_auto_20180905_0849'),
    ]

    operations = [
        migrations.AddField(
            model_name='business',
            name='loco',
            field=places.fields.PlacesField(default='Hunedoara', max_length=255),
        ),
        migrations.AlterField(
            model_name='business',
            name='location',
            field=models.CharField(max_length=140),
        ),
    ]
