# Generated by Django 2.1 on 2018-09-05 08:54

from django.db import migrations
import places.fields


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0096_auto_20180905_0853'),
    ]

    operations = [
        migrations.AlterField(
            model_name='business',
            name='loco',
            field=places.fields.PlacesField(max_length=255),
        ),
    ]
