# Generated by Django 2.1 on 2018-09-06 11:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0101_auto_20180906_1035'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='sender_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender_comment_select', to='business.CompanyBusiness'),
        ),
    ]
