# Generated by Django 2.1 on 2018-09-07 07:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0102_comment_sender_profile'),
    ]

    operations = [
        migrations.AddField(
            model_name='commentreply',
            name='sender_profile',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sender_reply_select', to='business.CompanyBusiness'),
        ),
    ]
