# Generated by Django 2.1 on 2018-09-07 08:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0104_auto_20180907_0809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='commentreply',
            name='comment_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment', to='business.Comment'),
        ),
    ]
